version: '3'

services:
  app:
    build:
      context: "./service"
      dockerfile: "Dockerfile"
    expose:  # Optional, exposes port for internal linking
      - 12345
    networks:
      - "app-network"
    environment:
      - SERVER_MESSAGE:"From app"
      - SERVER_PORT:"12435"
  web:
    build:
      context: "./webservice"
      dockerfile: "Dockerfile"
    expose:  # Optional, exposes port for internal linking
      - 5000
    networks:
      - "app-network"
    environment:
      - SERVER_MESSAGE:"From web"
      - SERVER_PORT:"5000"
  nginx:
    image: nginx:latest
    ports:
      - 80:80  # Host port:Container port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your Nginx config
    networks:
      - "app-network"

networks:
  app-network:
